- HankukUniversity/src/main/java/kr/or/hku/controller/common/LoginController.java
- HankukUniversity/src/main/java/kr/or/hku/service/common/ILoginService.java
- HankukUniversity/src/main/java/kr/or/hku/vo/LoginVO.java
- HankukUniversity/src/main/webapp/WEB-INF/views/admin/main.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/login/loginPage.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/portal/blank.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/portal/home.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/professor/main.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/main.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/system-template.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/tiles/header.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/tiles/sidebar.jsp
0706 로그인 & 로그아웃, 각 권한별 최초 페이지 작업
> Feat 로그인기능

- HankukUniversity/src/main/java/kr/or/hku/controller/student/CourseInfoController.java
- HankukUniversity/src/main/java/kr/or/hku/mapper/student/CourseInfoMapper.java
- HankukUniversity/src/main/java/kr/or/hku/service/student/CourseInfoServiceImpl.java
- HankukUniversity/src/main/java/kr/or/hku/service/student/ICourseInfoService.java
- HankukUniversity/src/main/java/kr/or/hku/vo/SubjectVO.java
- HankukUniversity/src/main/resources/sqlmap/courseInfo_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/mybatisAlias/mybatisAlias.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/student/search-subject.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/system-template.jsp
- HankukUniversity/src/main/webapp/resources/css/student/search-subject.css
- HankukUniversity/src/main/webapp/resources/css/style.css
- HankukUniversity/src/main/webapp/resources/css/table.css
> Feat 과목정보조회

- HankukUniversity/src/main/webapp/resources/css/table.css
> style: 주석제거

- HankukUniversity/src/main/java/kr/or/hku/common/mapper/CommonMapper.java
- HankukUniversity/src/main/java/kr/or/hku/common/service/ICommonService.java
- HankukUniversity/src/main/java/kr/or/hku/common/serviceImpl/CommonServiceImpl.java
- HankukUniversity/src/main/java/kr/or/hku/lectureInfo/controller/CourseInfoController.java
- HankukUniversity/src/main/java/kr/or/hku/lectureInfo/mapper/CourseInfoMapper.java
- HankukUniversity/src/main/java/kr/or/hku/lectureInfo/service/CourseInfoService.java
- HankukUniversity/src/main/java/kr/or/hku/lectureInfo/service/impl/CourseInfoServiceImpl.java
- HankukUniversity/src/main/java/kr/or/hku/lectureInfo/vo/CourseRegistVO.java
- HankukUniversity/src/main/java/kr/or/hku/lectureInfo/vo/LectureAplyVO.java
- HankukUniversity/src/main/java/kr/or/hku/student/vo/StudentVO.java
- HankukUniversity/src/main/resources/sqlmap/common_SQL.xml
- HankukUniversity/src/main/resources/sqlmap/courseInfo_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/mybatisAlias/mybatisAlias.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/student/course-record.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/present-course.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/search-subject.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/tiles/sidebar.jsp
- HankukUniversity/src/main/webapp/resources/css/student/course-info.css
> Feat 수강중인강의

- HankukUniversity/src/main/java/kr/or/hku/admin/controller/AcademicController.java
- HankukUniversity/src/main/java/kr/or/hku/common/service/CommonFileService.java
- HankukUniversity/src/main/java/kr/or/hku/common/serviceImpl/CommonFileServiceImpl.java
- HankukUniversity/src/main/java/kr/or/hku/notice/controller/AdminNoticeController.java
- HankukUniversity/src/main/java/kr/or/hku/notice/controller/DepartmentNoticeController.java
- HankukUniversity/src/main/java/kr/or/hku/notice/mapper/DepartmentNoticeMapper.java
- HankukUniversity/src/main/java/kr/or/hku/notice/service/DepartmentNoticeService.java
- HankukUniversity/src/main/java/kr/or/hku/notice/serviceImpl/DepartmentNoticeServiceImpl.java
- HankukUniversity/src/main/java/kr/or/hku/notice/vo/DeptNoticeVO.java
- HankukUniversity/src/main/java/kr/or/hku/notice/vo/PaginationInfoVO.java
- HankukUniversity/src/main/resources/sqlmap/deptNotice_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/mybatisAlias/mybatisAlias.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/admin/deptNotice.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/admin/notice.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/tiles/sidebar.jsp
> Feat 게시판관리

- HankukUniversity/src/main/java/kr/or/hku/admin/controller/AcademicController.java
- HankukUniversity/src/main/java/kr/or/hku/lectureInfo/vo/SubjectVO.java
- HankukUniversity/src/main/java/kr/or/hku/professor/controller/LectureController.java
- HankukUniversity/src/main/java/kr/or/hku/student/controller/StdGradeCheckController.java
- HankukUniversity/src/main/java/kr/or/hku/student/mapper/StdGradeCheckMapper.java
- HankukUniversity/src/main/java/kr/or/hku/student/service/StdGradeCheckService.java
- HankukUniversity/src/main/java/kr/or/hku/student/service/impl/StdGradeCheckServiceImpl.java
- HankukUniversity/src/main/java/kr/or/hku/student/vo/StudentInfoVO.java
- HankukUniversity/src/main/resources/sqlmap/stdGradeCheck_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/mybatisAlias/mybatisAlias.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/professor/lectureMng.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/stdGradeCheck.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/tiles/sidebar.jsp
- HankukUniversity/src/main/webapp/resources/css/student/std-jh.css
> Feat 학생성적조회

- HankukUniversity/src/main/java/kr/or/hku/admin/controller/UserManagementController.java
- HankukUniversity/src/main/java/kr/or/hku/common/service/impl/CommonFileServiceImpl.java
- HankukUniversity/src/main/webapp/WEB-INF/spring/root-context.xml
> chore:file path update

- HankukUniversity/src/main/java/kr/or/hku/admin/controller/UserManagementController.java
- HankukUniversity/src/main/java/kr/or/hku/admin/vo/FacilitiesVO.java
- HankukUniversity/src/main/java/kr/or/hku/student/controller/FaciltyReservationController.java
- HankukUniversity/src/main/java/kr/or/hku/student/mapper/FacilityMapper.java
- HankukUniversity/src/main/java/kr/or/hku/student/service/FacilityService.java
- HankukUniversity/src/main/java/kr/or/hku/student/service/impl/FacilityServiceImpl.java
- HankukUniversity/src/main/java/kr/or/hku/student/vo/LockerRsvtVO.java
- HankukUniversity/src/main/java/kr/or/hku/student/vo/StudentVO.java
- HankukUniversity/src/main/resources/sqlmap/facility_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/student/my-reservation.jsp
- HankukUniversity/src/main/webapp/resources/css/student/facility-rsvt.css
> Feat 나의예약현황

- HankukUniversity/src/main/java/kr/or/hku/admin/controller/UserManagementController.java
- HankukUniversity/src/main/java/kr/or/hku/admin/mapper/UserMapper.java
- HankukUniversity/src/main/java/kr/or/hku/admin/service/UserService.java
- HankukUniversity/src/main/java/kr/or/hku/admin/service/impl/UserServiceImpl.java
- HankukUniversity/src/main/resources/sqlmap/user_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/spring/root-context.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/admin/user-management.jsp
> Feat 사용자관리

- HankukUniversity/src/main/java/kr/or/hku/admin/controller/ScholarshipAdminController.java
- HankukUniversity/src/main/java/kr/or/hku/admin/mapper/ScholarshipMapper.java
- HankukUniversity/src/main/java/kr/or/hku/admin/service/ScholarshipService.java
- HankukUniversity/src/main/java/kr/or/hku/admin/service/impl/ScholarshipServiceImpl.java
- HankukUniversity/src/main/java/kr/or/hku/admin/vo/ScholarshipVO.java
- HankukUniversity/src/main/resources/sqlmap/scholarship_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/mybatisAlias/mybatisAlias.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/admin/sclsRegister.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/tiles/sidebar.jsp
> Feat 장학금관리

- HankukUniversity/src/main/java/kr/or/hku/admin/controller/CalendarAdminController.java
- HankukUniversity/src/main/java/kr/or/hku/admin/mapper/CalendarMapper.java
- HankukUniversity/src/main/java/kr/or/hku/admin/service/CalendarService.java
- HankukUniversity/src/main/java/kr/or/hku/admin/service/impl/CalendarServiceImpl.java
- HankukUniversity/src/main/java/kr/or/hku/admin/vo/CalendarVO.java
- HankukUniversity/src/main/java/kr/or/hku/common/controller/CalendarController.java
- HankukUniversity/src/main/java/kr/or/hku/common/vo/CalendarVO.java
- HankukUniversity/src/main/resources/sqlmap/adminCalendar_SQL.xml
- HankukUniversity/src/main/resources/sqlmap/scholarship_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/mybatisAlias/mybatisAlias.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/admin/calendar.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/tiles/sidebar.jsp
> Feat 학사일정관리

- HankukUniversity/src/main/webapp/WEB-INF/views/hku-portal.jsp
- HankukUniversity/src/main/webapp/resources/css/portal/default.css
> feat:메인포털 수정

- HankukUniversity/src/main/java/kr/or/hku/admin/controller/AcademicController.java
- HankukUniversity/src/main/java/kr/or/hku/admin/mapper/AcademicMapper.java
- HankukUniversity/src/main/java/kr/or/hku/admin/service/AcademicAdm.java
- HankukUniversity/src/main/java/kr/or/hku/admin/service/impl/AcademicAdmImpl.java
- HankukUniversity/src/main/java/kr/or/hku/admin/vo/AcademicChangeVO.java
- HankukUniversity/src/main/resources/sqlmap/academic_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/mybatisAlias/mybatisAlias.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/admin/academicFluctuation.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/tiles/sidebar.jsp
> feat:학적관리기능구현완

- HankukUniversity/src/main/java/kr/or/hku/classroom/controller/LectureNoticeController.java
- HankukUniversity/src/main/java/kr/or/hku/classroom/mapper/LectureNoticeMapper.java
- HankukUniversity/src/main/java/kr/or/hku/classroom/service/ILectureNoticeService.java
- HankukUniversity/src/main/java/kr/or/hku/classroom/service/LectureNoticeService.java
- HankukUniversity/src/main/java/kr/or/hku/classroom/serviceImpl/LectureNoticeServiceImpl.java
- HankukUniversity/src/main/java/kr/or/hku/classroom/vo/LectureNoticeVO.java
- HankukUniversity/src/main/resources/sqlmap/lectureNotice_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/professor/NewFile.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/professor/classroomMain.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/professor/lectureMng.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/professor/lectureNoticeDetail.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/professor/lectureNoticeForm.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/professor/lectureNoticeList.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/professor/restClass.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/lecturerNotice.jsp
- HankukUniversity/src/main/webapp/resources/css/classroom-jh.css
- HankukUniversity/src/main/webapp/resources/css/pro-jh.css
전체학기성적 조회 기능 및 클래스룸 공지사항 기능 완료
> Feat 전체학기성적조회

- HankukUniversity/src/main/java/kr/or/hku/admin/controller/FacilityController.java
- HankukUniversity/src/main/java/kr/or/hku/admin/mapper/FacilityManageMapper.java
- HankukUniversity/src/main/java/kr/or/hku/admin/service/FacilityManageService.java
- HankukUniversity/src/main/java/kr/or/hku/admin/service/impl/FacilityManageServiceImpl.java
- HankukUniversity/src/main/resources/sqlmap/facilityManage_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/mybatisAlias/mybatisAlias.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/admin/facility-administration.jsp
> feat:시설물관리, 시설예약관리 추가

- HankukUniversity/src/main/webapp/resources/css/portal/default.css
> feat:메인포털 css 수정

- HankukUniversity/src/main/webapp/WEB-INF/views/student/studyRoom.jsp
> fix:캘린더랜더링문제해결

- HankukUniversity/src/main/java/kr/or/hku/classroom/controller/testPresController.java
- HankukUniversity/src/main/java/kr/or/hku/common/controller/AlarmController.java
- HankukUniversity/src/main/java/kr/or/hku/common/controller/blankController.java
- HankukUniversity/src/main/java/kr/or/hku/common/mapper/CommonMapper.java
- HankukUniversity/src/main/java/kr/or/hku/common/service/CommonService.java
- HankukUniversity/src/main/java/kr/or/hku/common/service/impl/CommonServiceImpl.java
- HankukUniversity/src/main/java/kr/or/hku/common/vo/AlarmVO.java
- HankukUniversity/src/main/java/kr/or/hku/counseling/controller/CounselingController.java
- HankukUniversity/src/main/java/kr/or/hku/counseling/service/CounselingService.java
- HankukUniversity/src/main/java/kr/or/hku/counseling/service/impl/CounselingServiceImpl.java
- HankukUniversity/src/main/java/kr/or/hku/student/controller/FaciltyReservationController.java
- HankukUniversity/src/main/resources/sqlmap/common_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/spring/security-context.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/open-test.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/professor/student-counseling-record.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/professor/test-form.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/counseling-record.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/counseling-req.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/course-record.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/course-req.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/facility-rsvt.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/locker-rsvt.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/my-reservation.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/present-course.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/search-subject.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/test-info.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/tiles/header.jsp
> Feat 정수시큐리티

- HankukUniversity/src/main/webapp/WEB-INF/views/hku-portal.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/system-template.jsp
> feat:toastr설정추가

- HankukUniversity/src/main/java/kr/or/hku/lectureInfo/vo/SubjectVO.java
- HankukUniversity/src/main/resources/sqlmap/courseInfo_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/student/search-subject.jsp
- HankukUniversity/src/main/webapp/resources/css/student/course-info.css
> Feat 무한스크롤

- HankukUniversity/src/main/java/kr/or/hku/student/controller/TuitionController.java
- HankukUniversity/src/main/java/kr/or/hku/student/mapper/TuitionMapper.java
- HankukUniversity/src/main/java/kr/or/hku/student/service/TuitionService.java
- HankukUniversity/src/main/java/kr/or/hku/student/service/impl/TuitionServiceImpl.java
- HankukUniversity/src/main/resources/sqlmap/tuition_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/student/tuition-bill.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/tuition-payment-details.jsp
- HankukUniversity/src/main/webapp/resources/css/student/tut-bill.css
> Feat 등록금납부내역

- HankukUniversity/src/main/java/kr/or/hku/student/controller/CertificateController.java
- HankukUniversity/src/main/java/kr/or/hku/student/mapper/CertificateMapper.java
- HankukUniversity/src/main/java/kr/or/hku/student/service/CertificateService.java
- HankukUniversity/src/main/java/kr/or/hku/student/service/impl/CertificateServiceImpl.java
- HankukUniversity/src/main/resources/sqlmap/certificate_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/student/certificate-list.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/certificate.jsp
> feat:기능 보완 및 수정

- HankukUniversity/src/main/java/kr/or/hku/student/service/impl/TuitionServiceImpl.java
> feat:itext기능개선

- HankukUniversity/src/main/java/kr/or/hku/login/controller/LoginController.java
- HankukUniversity/src/main/java/kr/or/hku/portal/controller/blankController3.java
- HankukUniversity/src/main/java/kr/or/hku/portal/mapper/blankMapper3.java
- HankukUniversity/src/main/java/kr/or/hku/portal/service/blankService3.java
- HankukUniversity/src/main/java/kr/or/hku/portal/service/impl/PortalServiceImpl.java
- HankukUniversity/src/main/java/kr/or/hku/portal/service/impl/blankServiceImpl3.java
- HankukUniversity/src/main/java/kr/or/hku/portal/vo/blankVO3.java
- HankukUniversity/src/main/java/kr/or/hku/student/vo/StudentVO.java
- HankukUniversity/src/main/resources/sqlmap/common_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/hku-portal.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/portal/blank.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/portal/home.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/course-record.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/course-req.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/facility-rsvt.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/locker-rsvt.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/present-course.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/search-subject.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/tiles/nav-header.jsp
- HankukUniversity/src/main/webapp/resources/css/home-pjs.css
- HankukUniversity/src/main/webapp/resources/css/portal/default.css
- HankukUniversity/src/main/webapp/resources/js/custom.js
포탈 메인에 나의 시간표 및 학사 학과 일정 추가했습니다.
> Feat 포탈메인작업

- HankukUniversity/src/main/java/kr/or/hku/student/controller/ScholarshipController.java
- HankukUniversity/src/main/java/kr/or/hku/student/vo/StdScholarshipVO.java
- HankukUniversity/src/main/webapp/WEB-INF/views/student/scholarship-apply.jsp
> feat:장학금 증빙파일 수정 기능

- HankukUniversity/src/main/java/kr/or/hku/admin/controller/UserManagementController.java
- HankukUniversity/src/main/webapp/WEB-INF/views/admin/user-management.jsp
- HankukUniversity/src/main/webapp/resources/css/admin/userManage.css
> Feat 장학금신청

- HankukUniversity/src/main/java/kr/or/hku/login/controller/LoginController.java
- HankukUniversity/src/main/java/kr/or/hku/portal/controller/PortalController.java
- HankukUniversity/src/main/webapp/WEB-INF/views/admin/deptNotice.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/admin/notice.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/hku-portal.jsp
> Fix 최초로그인오류수정

- HankukUniversity/src/main/java/kr/or/hku/login/controller/LoginController.java
> fix:로그인버그수정

- HankukUniversity/src/main/java/kr/or/hku/admin/controller/UserManagementController.java
- HankukUniversity/src/main/java/kr/or/hku/common/mapper/CommonSMSMapper.java
- HankukUniversity/src/main/java/kr/or/hku/common/service/CommonSMSService.java
- HankukUniversity/src/main/java/kr/or/hku/common/service/impl/CommonSMSServiceImpl.java
- HankukUniversity/src/main/resources/sqlmap/commonSms_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/admin/sendTextMsg.jsp
> feat_문자추가수정 기능추가

- HankukUniversity/src/main/java/kr/or/hku/admin/controller/UserManagementController.java
- HankukUniversity/src/main/webapp/WEB-INF/views/admin/user-management.jsp
- HankukUniversity/src/main/webapp/resources/css/admin/userManage.css
feat:사용자 등록 비밀번호 security 설정 및 일괄 등록 버튼 변경
> feat:사용자 등록 비밀번호 security 설정 및 일괄등록 버튼 변경

- HankukUniversity/src/main/webapp/WEB-INF/views/admin/totalChart.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/tiles/chatbox.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/tiles/header.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/tiles/nav-header.jsp
> Feat 채팅방스타일

- HankukUniversity/src/main/java/kr/or/hku/admin/controller/AcademicController.java
- HankukUniversity/src/main/java/kr/or/hku/admin/controller/FacilityController.java
- HankukUniversity/src/main/java/kr/or/hku/admin/controller/LockerController.java
- HankukUniversity/src/main/java/kr/or/hku/admin/controller/UserManagementController.java
- HankukUniversity/src/main/java/kr/or/hku/student/controller/CertificateController.java
- HankukUniversity/src/main/java/kr/or/hku/student/controller/ScholarshipController.java
- HankukUniversity/src/main/java/kr/or/hku/student/controller/TuitionController.java
- HankukUniversity/src/main/webapp/WEB-INF/views/admin/excelUserInsert.jsp
- HankukUniversity/src/main/webapp/resources/css/admin/userManage.css
> feat:기능보완 및 개선

- HankukUniversity/src/main/java/kr/or/hku/student/controller/StudyController.java
- HankukUniversity/src/main/resources/sqlmap/study_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/portal/studyBoard.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/portal/studyBoardDetail.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/tiles/chatbox.jsp
> feat.에러잡아죽였어용

- HankukUniversity/src/main/webapp/WEB-INF/views/portal/studyBoard.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/portal/studyBoardDetail.jsp
> style.css수정

- HankukUniversity/src/main/webapp/WEB-INF/views/admin/user-management.jsp
> Feat 기능보완및개선

- HankukUniversity/src/main/java/kr/or/hku/student/controller/StudyBoardController.java
- HankukUniversity/src/main/java/kr/or/hku/student/mapper/StudyMapper.java
- HankukUniversity/src/main/java/kr/or/hku/student/service/StudyService.java
- HankukUniversity/src/main/java/kr/or/hku/student/service/impl/StudyServiceImpl.java
- HankukUniversity/src/main/resources/sqlmap/study_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/portal/studyBoardDetail.jsp
> Feat 인원수제한

- HankukUniversity/src/main/webapp/WEB-INF/views/admin/calendar.jsp
> 학사일정관리 자동완성버튼생성

- HankukUniversity/src/main/java/kr/or/hku/common/service/CommonFileService.java
- HankukUniversity/src/main/java/kr/or/hku/common/service/impl/CommonFileServiceImpl.java
- HankukUniversity/src/main/java/kr/or/hku/student/controller/StudyBoardController.java
- HankukUniversity/src/main/resources/sqlmap/study_SQL.xml
- HankukUniversity/src/main/webapp/WEB-INF/views/portal/studyBoard.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/study.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/studyRoom.jsp
> Feat 스터디수정햄

- HankukUniversity/src/main/java/kr/or/hku/common/service/impl/CommonSMSServiceImpl.java
- HankukUniversity/src/main/webapp/WEB-INF/views/portal/studyBoard.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/professor/student-counseling-record.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/studyRoom.jsp
> Feat 잡다한수정

- HankukUniversity/src/main/resources/sqlmap/lectureNotice_SQL.xml
> Fix sql오류수정

- HankukUniversity/src/main/webapp/WEB-INF/views/student/studyRoom.jsp
> Fix 스터디룸일정

- HankukUniversity/src/main/webapp/WEB-INF/views/professor/assignmentDetail.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/professor/classroomMain.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/professor/gradeTable.jsp
- HankukUniversity/src/main/webapp/WEB-INF/views/student/assignmentDetail.jsp
> Feat 스타일수정

- HankukUniversity/src/main/webapp/WEB-INF/views/admin/scholarshipAplyList.jsp
> Feat 알러트수정
